"""Install the bundled CLI reference into the user's docs vault.

The CLI reference is generated by ``scripts/gen_cli_docs.py`` and bundled
inside the wheel under ``dosm/cli_docs/`` (via ``force-include`` in
``pyproject.toml``). This module copies the bundle into
``$DOSM_HOME/docs/_dosm-cli/`` so the docs indexer picks it up and the
agent can find CLI knowledge through normal RAG retrieval.

Files include YAML frontmatter ``folder: dosm-cli`` so the indexer
associates them to the ``DOSM-CLI`` Folder row that
:func:`ensure_cli_folder` seeds. The result is a dedicated folder in the
Docs UI rather than a pile of entries in Unfiled.

Falls back to the in-repo source path when running from an editable
install where the wheel-only ``cli_docs`` directory does not exist.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from sqlalchemy.orm import Session

VAULT_SUBDIR = "_dosm-cli"
FOLDER_SLUG = "dosm-cli"
FOLDER_NAME = "DOSM-CLI"
FOLDER_DESCRIPTION = (
    "Reference for the dosm CLI. Auto-generated and refreshed by "
    "`dosm docs install-cli-reference`. Do not hand-edit; changes are "
    "overwritten on the next install."
)

_PKG_DIR = Path(__file__).resolve().parent.parent  # .../dosm/


def _bundled_root() -> Path:
    """Find the root containing README.md, exit-codes.md, and _generated/."""
    wheel = _PKG_DIR / "cli_docs"
    if (wheel / "_generated").is_dir():
        return wheel
    repo = _PKG_DIR.parent / "docs" / "cli"
    if (repo / "_generated").is_dir():
        return repo
    raise FileNotFoundError(
        "Could not locate bundled CLI docs. Searched:\n"
        f"  {wheel}\n  {repo}\n"
        "If running from source, run: python scripts/gen_cli_docs.py"
    )


def install_cli_reference(target_docs_dir: Path) -> tuple[int, Path]:
    """Copy bundled CLI docs into ``target_docs_dir / _dosm-cli/``.

    Overwrites any existing contents — this folder is owned by DOSM and
    must not be hand-edited. ``_generated/<group>.md`` files are flattened
    into the target directory so the indexer treats them as siblings of
    the README and exit-codes pages.

    Returns ``(file_count, target_dir)``.
    """
    src = _bundled_root()
    target = target_docs_dir / VAULT_SUBDIR
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)

    count = 0
    for top_level in ("README.md", "exit-codes.md"):
        src_file = src / top_level
        if src_file.is_file():
            shutil.copy2(src_file, target / top_level)
            count += 1

    generated = src / "_generated"
    for md in sorted(generated.glob("*.md")):
        shutil.copy2(md, target / md.name)
        count += 1

    # Stamp file lets `dosm init` skip re-installing on every run.
    (target / ".dosm-cli-version").write_text(_version_stamp(), encoding="utf-8")
    return count, target


def _version_stamp() -> str:
    from dosm import __version__

    return __version__ + "\n"


def is_current(target_docs_dir: Path) -> bool:
    """True if ``_dosm-cli/`` exists and matches the running DOSM version."""
    stamp = target_docs_dir / VAULT_SUBDIR / ".dosm-cli-version"
    if not stamp.is_file():
        return False
    try:
        return stamp.read_text(encoding="utf-8").strip() == _version_stamp().strip()
    except OSError:
        return False


def ensure_cli_folder(session: Session) -> None:
    """Create or update the DOSM-CLI Folder row. Idempotent.

    Called from ``dosm docs install-cli-reference`` and ``dosm db init`` so
    the Folder exists before the indexer encounters frontmatter referencing
    its slug. Without this row, generated pages would land in Unfiled.
    """
    from dosm.docs_index import applications as folder_repo

    existing = folder_repo.get_folder_by_slug(session, FOLDER_SLUG)
    if existing is None:
        folder_repo.create_folder(
            session,
            name=FOLDER_NAME,
            slug=FOLDER_SLUG,
            description=FOLDER_DESCRIPTION,
        )
        return
    # Keep name/description in sync if a previous version drifted.
    if existing.name != FOLDER_NAME or (existing.description or "") != FOLDER_DESCRIPTION:
        folder_repo.update_folder(
            session,
            existing,
            name=FOLDER_NAME,
            description=FOLDER_DESCRIPTION,
        )
